-- q022: revenue by support rep
-- Category: employees
-- Description: Calculates the total revenue generated by each support representative based on the invoices of the customers they support.

SELECT e.FirstName || ' ' || e.LastName AS support_rep_name, SUM(i.Total) AS total_revenue FROM Employee e JOIN Customer c ON e.EmployeeId = c.SupportRepId JOIN Invoice i ON c.CustomerId = i.CustomerId GROUP BY e.EmployeeId ORDER BY total_revenue DESC LIMIT 10;
