from __future__ import annotations

import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
QUERIES_DIR = PROJECT_ROOT / "queries"


Q051 = {
    "query_id": "q051",
    "category": "artists",
    "intent": "revenue for specific artist",
    "description": "Returns total track sales revenue for one requested artist.",
    "sample_questions": [
        "What is the revenue for Iron Maiden?",
        "How much revenue did U2 generate?",
        "Show total sales revenue for a specific artist.",
    ],
    "sql": """
SELECT ar.Name AS artist_name,
       ROUND(COALESCE(SUM(il.UnitPrice * il.Quantity), 0), 2) AS total_revenue
FROM Artist ar
LEFT JOIN Album a ON ar.ArtistId = a.ArtistId
LEFT JOIN Track t ON a.AlbumId = t.AlbumId
LEFT JOIN InvoiceLine il ON t.TrackId = il.TrackId
WHERE ar.Name = :artist_name
GROUP BY ar.ArtistId
""".strip(),
    "expected_columns": ["artist_name", "total_revenue"],
    "tables_used": ["Artist", "Album", "Track", "InvoiceLine"],
    "parameters": [
        {
            "name": "artist_name",
            "type": "artist_name",
            "required": True,
            "description": "Artist name available in the database.",
        }
    ],
}


Q051_VARIATIONS = [
    "What is the revenue for Iron Maiden?",
    "How much revenue did U2 generate?",
    "Show total sales revenue for a specific artist.",
    "artist revenue for Metallica",
    "how much money did Led Zeppelin make",
    "total sales for Iron Maiden",
    "revenue generated by a named artist",
    "what did U2 earn from track sales",
    "sales revenue for artist",
    "how much revenue for R.E.M.",
    "his revenue after artist result",
    "how much is that artist revenue",
    "artist revnue total",
    "money made by iron maiden",
    "sales for u2 pls",
    "how much did the artist make",
    "revenue for this singer",
]


def read_json(path: Path) -> list[dict]:
    with path.open("r", encoding="utf-8") as file:
        payload = json.load(file)
    if not isinstance(payload, list):
        raise ValueError(f"{path} must contain a JSON array")
    return payload


def write_json(path: Path, payload: list[dict]) -> None:
    with path.open("w", encoding="utf-8") as file:
        json.dump(payload, file, indent=2, ensure_ascii=False)
        file.write("\n")


def merge_one(existing: list[dict], entry: dict) -> list[dict]:
    merged = [item for item in existing if item.get("query_id") != entry["query_id"]]
    merged.append(entry)
    return sorted(merged, key=lambda item: int(item["query_id"][1:]))


def description_entry() -> dict:
    return {
        "query_id": Q051["query_id"],
        "category": Q051["category"],
        "intent": Q051["intent"],
        "selected_candidate_id": "q051_manual",
        "selected_strategy": "manual_context_follow_up",
        "source": "manual_context_query_pack",
        "description": Q051["description"],
        "original_description": Q051["description"],
        "sql": Q051["sql"],
        "expected_columns": Q051["expected_columns"],
        "tables_used": Q051["tables_used"],
    }


def variation_entry() -> dict:
    return {
        "query_id": Q051["query_id"],
        "category": Q051["category"],
        "intent": Q051["intent"],
        "description": Q051["description"],
        "user_queries": Q051_VARIATIONS,
    }


def sql_file_text() -> str:
    return (
        f"-- {Q051['query_id']}: {Q051['intent']}\n"
        f"-- Category: {Q051['category']}\n"
        f"-- Description: {Q051['description']}\n"
        "-- Parameter: artist_name (artist_name) - Artist name available in the database.\n\n"
        f"{Q051['sql'].strip().rstrip(';')};\n"
    )


def main() -> None:
    if len(Q051_VARIATIONS) != 17:
        raise ValueError("q051 must have 17 user-query variations")

    repository = merge_one(read_json(DATA_DIR / "query_repository.json"), Q051)
    descriptions = merge_one(read_json(DATA_DIR / "optimized_descriptions.json"), description_entry())
    variations = merge_one(read_json(DATA_DIR / "user_query_variations.json"), variation_entry())

    write_json(DATA_DIR / "query_repository.json", repository)
    write_json(DATA_DIR / "optimized_descriptions.json", descriptions)
    write_json(DATA_DIR / "user_query_variations.json", variations)

    QUERIES_DIR.mkdir(parents=True, exist_ok=True)
    (QUERIES_DIR / "q051.sql").write_text(sql_file_text(), encoding="utf-8")

    print("Synced context query pack")
    print(f"Repository entries: {len(repository)}")
    print(f"Optimized descriptions: {len(descriptions)}")
    print(f"User-query variation entries: {len(variations)}")
    print("SQL files written: 1")


if __name__ == "__main__":
    main()
